# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andre Rocha
email: andrematheus94@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi there! My name is Andre Rocha and this is my site. I will write mostly
  about programming here, but if anything else interesting comes to mind I
  might put it here too.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: amrocha

# Build settings
markdown: kramdown
